# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-03 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dico', '0002_definitionvote_wordvote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefinitionVote',
            new_name='Vote',
        ),
        migrations.RemoveField(
            model_name='wordvote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wordvote',
            name='word',
        ),
        migrations.DeleteModel(
            name='WordVote',
        ),
    ]
